### ISSUE TITLE
kinematicsCad.groovy  fails with the following error

### ISSUE THREAD

**Issue by acamilo** [NeuronRobotics/BowlerStudio#2]
kinematicsCad.groovy 
groovy.lang.MissingMethodException: No signature of method: com.neuronrobotics.sdk.addons.kinematics.DHParameterKinematics.setScriptingName() is applicable for argument types: (java.lang.String) values: [DHArm]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:56)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at Script1.run(Script1.groovy:6)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngineWidget.runGroovy(ScriptingEngineWidget.java:584)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngineWidget.inlineScriptRun(ScriptingEngineWidget.java:663)
	at com.neuronrobotics.bowlerstudio.scripting.ScriptingEngineWidget$1.run(ScriptingEngineWidget.java:306)

**Comment by ParonoidAndroid** [comment]
wut

**Comment by madhephaestus** [comment]
solved in new release
