### ISSUE TITLE
bs 0.4.22 fails to launch w jvm 1.8.0_60 on osx 10.8.5

### ISSUE THREAD

**Issue by acamilo** [NeuronRobotics/BowlerStudio#57]
Last login: Thu Dec 24 21:59:57 on ttys000
fackcamilo:~ Acamilo$ top
fackcamilo:~ Acamilo$ ps -A | grep java
  846 ttys000    0:00.00 grep java
fackcamilo:~ Acamilo$ ps -A | grep java
  857 ??         0:03.42 /usr/bin/java -jar /Users/Acamilo/Downloads/bowlerstudio-0.4.22/BowlerStudio.app/Contents/MacOS/bin/BowlerStudio.jar
  860 ttys000    0:00.00 grep java
fackcamilo:~ Acamilo$ /usr/bin/java -jar /Users/Acamilo/Downloads/bowlerstudio-0.4.22/BowlerStudio.app/Contents/MacOS/bin/BowlerStudio.jar
fackcamilo:~ Acamilo$ /usr/bin/java -jar /Users/Acamilo/Downloads/bowlerstudio-0.4.22/BowlerStudio.app/Contents/MacOS/bin/BowlerStudio.jar
fackcamilo:~ Acamilo$ /usr/bin/java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
fackcamilo:~ Acamilo$ /usr/bin/java -jar /Users/Acamilo/Downloads/bowlerstudio-0.4.22/BowlerStudio.app/Contents/MacOS/bin/BowlerStudio.jar aaa
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: OPENCV_DIR was not found, environment variable OPENCV_DIR needs to be set
	at com.neuronrobotics.imageprovider.OpenCVJNILoader.load(OpenCVJNILoader.java:60)
	at com.neuronrobotics.bowlerstudio.BowlerStudio.main(BowlerStudio.java:72)
	... 11 more
Exception running application com.neuronrobotics.bowlerstudio.BowlerStudio
fackcamilo:~ Acamilo$

**Comment by madhephaestus** [comment]
OPENCV_DIR was not found, environment variable OPENCV_DIR needs to be set

means you should run the shell script 'BowlerStudio', as the .app does, in the contents directory, or set your environment variable for OpenCV gloabally.
